version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-video-editor-backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/outputs:/app/outputs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-video-editor-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
